### ISSUE TITLE
Add support for HTMX attribute hx-include

### ISSUE THREAD

**Issue by henhuy** [benopotamus/htmx-ext-shoelace#8]
In my project, I trigger HTMX from a single button (which is not included in any form) and include form inputs from multiple other forms by using HTMX attribute `hx-include` (see in HTMX doc: https://htmx.org/attributes/hx-include/).

I will add a PR which tries to solve this issue...

**Comment by benopotamus** [comment]
This appears to be working in htmx 2.0 without any coercing by this shoelace extension :partying_face:
